#!/usr/bin/env lua

local MODULES = {
    { name = "cli", path = "src/cli.lua" },
    { name = "lexer", path = "src/lexer.lua" },
    { name = "parser", path = "src/parser.lua" },
    { name = "scope_resolver", path = "src/scope_resolver.lua" },
    { name = "stdlib_analyzer", path = "src/stdlib_analyzer.lua" },
    { name = "stdlib_selector", path = "src/stdlib_selector.lua" },
    { name = "ITranspiler", path = "src/ITranspiler.lua" },
    { name = "stdlib.bash.base", path = "src/stdlib/bash/base.lua" },
    { name = "stdlib.bash.io", path = "src/stdlib/bash/io.lua" },
    { name = "stdlib.bash.math", path = "src/stdlib/bash/math.lua" },
    { name = "stdlib.bash.os", path = "src/stdlib/bash/os.lua" },
    { name = "stdlib.bash.string", path = "src/stdlib/bash/string.lua" },
    { name = "stdlib.bash.table", path = "src/stdlib/bash/table.lua" },
    { name = "stdlib.powershell.base", path = "src/stdlib/powershell/base.lua" },
    { name = "stdlib.powershell.io", path = "src/stdlib/powershell/io.lua" },
    { name = "stdlib.powershell.math", path = "src/stdlib/powershell/math.lua" },
    { name = "stdlib.powershell.os", path = "src/stdlib/powershell/os.lua" },
    { name = "stdlib.powershell.string", path = "src/stdlib/powershell/string.lua" },
    { name = "stdlib.powershell.table", path = "src/stdlib/powershell/table.lua" },
    { name = "bash_transpiler", path = "src/bash_transpiler.lua" },
    { name = "ps1_transpiler", path = "src/ps1_transpiler.lua" },
    { name = "__luash_core", path = "src/luash.lua" },
}

local SOURCE_FILES = {
    "main.lua",
    "run_build.lua",
    "run_check.lua",
    "run_tests.lua",
    "src/cli.lua",
    "src/lexer.lua",
    "src/parser.lua",
    "src/scope_resolver.lua",
    "src/stdlib_analyzer.lua",
    "src/stdlib_selector.lua",
    "src/ITranspiler.lua",
    "src/stdlib/bash/base.lua",
    "src/stdlib/bash/io.lua",
    "src/stdlib/bash/math.lua",
    "src/stdlib/bash/os.lua",
    "src/stdlib/bash/string.lua",
    "src/stdlib/bash/table.lua",
    "src/stdlib/powershell/base.lua",
    "src/stdlib/powershell/io.lua",
    "src/stdlib/powershell/math.lua",
    "src/stdlib/powershell/os.lua",
    "src/stdlib/powershell/string.lua",
    "src/stdlib/powershell/table.lua",
    "src/bash_transpiler.lua",
    "src/ps1_transpiler.lua",
    "src/luash.lua",
}

local function readFile(path)
    local file, err = io.open(path, "rb")
    assert(file, "Build Error: cannot read " .. path .. ": " .. tostring(err))
    local content = file:read("*a")
    file:close()
    local normalized = content:gsub("\r\n", "\n")
    return normalized
end

local function writeFile(path, content)
    local file, err = io.open(path, "wb")
    assert(file, "Build Error: cannot write " .. path .. ": " .. tostring(err))
    file:write(content)
    file:close()
end

local function ensureDistDirectory()
    local separator = package.config:sub(1, 1)
    local command = separator == "\\" and 'if not exist "dist" mkdir "dist"' or 'mkdir -p "dist"'
    local ok = os.execute(command)
    assert(ok == true or ok == 0, "Build Error: could not create dist directory")
end

local function syntaxCheck(path)
    local chunk, err = loadfile(path)
    assert(chunk, "Syntax Error in " .. path .. ": " .. tostring(err))
end

local function buildBundle()
    local chunks = {
        "#!/usr/bin/env lua\n",
        "-- Generated by run_build.lua. Do not edit this file directly.\n",
        "-- Luash 0.1.0-alpha: dependency-free CLI and reusable module.\n\n",
    }
    for _, module in ipairs(MODULES) do
        table.insert(chunks, "package.preload[" .. string.format("%q", module.name) .. "] = function(...)\n")
        table.insert(chunks, readFile(module.path))
        table.insert(chunks, "\nend\n\n")
    end
    table.insert(
        chunks,
        [[local __luash = require("__luash_core")
local __loadedAs = ...
if type(__loadedAs) == "string" and __loadedAs:match("luash$") and not __loadedAs:match("^%-") then
    return __luash
end
local __exitCode = __luash.main(arg or {})
if __exitCode ~= 0 then
    os.exit(__exitCode)
end
return __luash
]]
    )
    ensureDistDirectory()
    writeFile("dist/luash.lua", table.concat(chunks))
end

print("=== Luash Build ===")
for _, path in ipairs(SOURCE_FILES) do
    syntaxCheck(path)
end
buildBundle()
syntaxCheck("dist/luash.lua")

package.path = "src/?.lua;src/?/init.lua;" .. package.path
local Luash = require("luash")
local bash = Luash.transpile("local x = 1 + 2\nprint(x)", "bash")
local ps1 = Luash.transpile("local x = 1 + 2\nprint(x)", "ps1")
assert(bash:find("#!/usr/bin/env bash", 1, true) == 1, "Build Error: Bash smoke test failed")
assert(ps1:find("Write-Output", 1, true), "Build Error: PowerShell smoke test failed")

print("Built dist/luash.lua (standalone CLI + require-able module)")
print("=== BUILD SUCCESSFUL ===")
